kind: Deployment
apiVersion: apps/v1
metadata:
  name: covid-tracker
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      name: my-pod
      labels:
        app: my-app
    spec:
      containers:
      - name: covidc
        image: anshustwt/covidi
        imagePullPolicy: Always
        ports:
        - containerPort: 3000